# Generated by Django 5.0.4 on 2024-12-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sequence', models.PositiveIntegerField()),
                ('mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('linkedin_profile', models.URLField()),
                ('emails', models.TextField()),
                ('phone_numbers', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('communication_periodicity', models.PositiveIntegerField(default=14)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.communicationmethod')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='communications.company')),
            ],
        ),
    ]
