# Generated by Django 5.0.4 on 2024-12-31 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='company',
            name='communication_periodicity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='company',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_numbers',
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='communications.company'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='communications.communicationmethod'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='sequence',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
