# Generated by Django 5.0.4 on 2024-12-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_communicationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='communication_periodicity',
            field=models.IntegerField(default=14, help_text='Default interval in days for scheduled communications.'),
        ),
        migrations.AddField(
            model_name='company',
            name='emails',
            field=models.TextField(default='', help_text='Enter multiple emails separated by commas.'),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_numbers',
            field=models.TextField(default='', help_text='Enter multiple phone numbers separated by commas.'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
